### ISSUE TITLE
Trust Wallet Connect Wallet problem

### ISSUE THREAD

**Issue by kiaxseventh** [gochain/flutter_web3_provider#1]
on the **Trust Wallet**  Connect Wallet button example do not work
but sign and verify is ok and dont have any problem

**Comment by treeder** [comment]
Trust Wallet has some issues with flutter apps, the ethereum object doesn't seem to get injected properly. I've let them know about it so we'll see. Test example I sent them is here: https://trust-test-4f535.web.app/

**Comment by kiaxseventh** [comment]
now this your example link have problem on android metamask and chrome extention !

please check it
https://trust-test-4f535.web.app/

thank you lot of

**Comment by treeder** [comment]
Works for me. What problem do you see?

**Comment by kiaxseventh** [comment]
![Screenshot_20201104-000443_MetaMask](https://user-images.githubusercontent.com/15640035/98037993-ab3c0400-1e31-11eb-97cd-33f7c74ad427.jpg)

**Comment by kiaxseventh** [comment]
of course, this page message was viewed after several refreshments

![Screenshot_20201104-000815_MetaMask](https://user-images.githubusercontent.com/15640035/98038222-02da6f80-1e32-11eb-8b2c-0fb8633b4874.jpg)

**Comment by treeder** [comment]
Hmmm, on Metamask mobile, looks like first load it fails, then every refresh it seems to work. 🤷  Chrome extension always works. Flutter seems to mess with it in some way.

**Comment by treeder** [comment]
So there's bigger issues here, not flutter related. Metamask has the same issues and they are aware of it. You can follow it here: https://github.com/MetaMask/metamask-mobile/issues/1975

**Comment by pinpong** [comment]
Hello, my dApp is also not able to connect with in build-in browser from Trustwallet Android app. Any idea?

**Comment by treeder** [comment]
Not sure if Trust has fixed this issue yet, seems to be fixed in Metamask now though. Does it work with Metamask mobile?

**Comment by pinpong** [comment]
It is working on metaMask mobil.

**Comment by pinpong** [comment]
@treeder please close the issue.

https://github.com/trustwallet/trust-web3-provider/issues/139

**Comment by treeder** [comment]
Is it fixed?

**Comment by pinpong** [comment]
No but thus issue is not related to that lib.
