### ISSUE TITLE
Help on read response value

### ISSUE THREAD

**Issue by secmask** [gochain/flutter_web3_provider#10]
I'm a flutter beginner and try using this lib, I'm follow the example, it works well. There's a bit I need your help, to convert response into Dart value, say
```
var res =
    await promiseToFuture(callMethod(contract, "transfer", [
    '0x39C5190c09ec04cF09C782bA4311C469473Ffe83',
    "0x" + amount.toString()).toRadixString(16)
    ]));
```

1. `res` is an object, I don't know how to read `tx` from it?
2. when above call raise exception, again I receive an object with `catch`, how do I read `message` in it?

Thank you!

**Comment by treeder** [comment]
Print it and see what you get back.

**Comment by secmask** [comment]
print only get `Object object`, but I found a way to read it using `hasProperty` and `getProperty` in `js_util` but I need to guess field name to make it work.

**Comment by pinpong** [comment]
Hi,

add
```js
@JS("JSON.stringify")
external String stringify(obj);
```
to the ethereum.dart and use with

```js
json.decode(stringify(e))["data"]["message"]
```

will provide a PR asap

**Comment by secmask** [comment]
I tested and works, thank you.
