### ISSUE TITLE
Read Only Provider

### ISSUE THREAD

**Issue by eakdogan** [gochain/flutter_web3_provider#11]
How can I use a read only provider to call a method (from mobile browser for example).
I tried:
var readProvider = new JsonRpcProvider("https://rpc.gochain.io");
    contract = Contract(contractAddress, abi, readProvider);
    data = promiseToFuture(callMethod(contract, "getData", []));

But I get a "call revert exception". The call works well with web3 provider. 

Thank you!

**Comment by treeder** [comment]
If it's read only, I'd probably just use (web3dart)[https://github.com/simolus3/web3dart]
