### ISSUE TITLE
How to include another contract as dependency?

### ISSUE THREAD

**Issue by EightRice** [gochain/flutter_web3_provider#20]
Is there a way to deploy in a Parent/Child type of situation? How would you specify another contract in the List object that you use to declare the contract you want to call? 
Here's the issue in more details https://stackoverflow.com/questions/66891008/how-to-include-another-contract-as-dependency

**Comment by treeder** [comment]
You can certainly deploy things like this by passing in the address of the parent when you deploy the child. But this library is not for deploying so closing. Check out web3 cli for easy deploying: https://github.com/gochain/web3
