### ISSUE TITLE
Notify transaction state

### ISSUE THREAD

**Issue by EightRice** [gochain/flutter_web3_provider#21]
I'm trying to call functions in a smart contract sequentially and they need to finish executing between calls.  Is there a way to know when a transaction went through?

**Comment by pinpong** [comment]
```js
        final transaction =
            await promiseToFuture(callMethod(contract, "your_method", []));
        final hash = json.decode(stringify(transaction))?["hash"];

        final result = await promiseToFuture(
            callMethod(_web3, "waitForTransaction", [hash]));

        if (json.decode(stringify(result))?["status"] == 0) {
          throw TransactionFailedException();
        }

**Comment by EightRice** [comment]
Thank you so much @pinpong , this works great. 
Looking at the `json.decode(stringify(result)`, it has lots of attributes like "to", "from", etc, but I can't see the actual return value of the smart contract function. Do you know how I can access that?

**Comment by Jonathan-Livingston-Seagull** [comment]
@pinpong I am searching for flutter/dart web3 solution and found out this nice package. I am just wondering if you guys are supporting this project still, as the issues are in open state for long time.

**Comment by treeder** [comment]
Yes, it's supported. The response to this is that there is no response to write function. If it's successful, you know it went through and you can then check the state. For instance, after a "transfer" function is called and successful, call "balanceOf" to check balances.

**Comment by EightRice** [comment]
> Yes, it's supported. The response to this is that there is no response to write function. If it's successful, you know it went through and you can then check the state. For instance, after a "transfer" function is called and successful, call "balanceOf" to check balances.

So you have a function in a smart contract that returns a string value, but when calling that function through the flutter app you can't get the return value.. Is that what you're saying?

**Comment by treeder** [comment]
Yes that's what I'm saying, but not just flutter, it's how the blockchain works. You can either do what I said, or emit events in your function and read those later. 

* https://ethereum.stackexchange.com/questions/58228/return-function-value-instead-of-transaction-receipt-with-web3/58236
* https://ethereum.stackexchange.com/questions/15704/how-to-get-return-value-of-function-for-solidity-contract?rq=1
* https://stackoverflow.com/questions/61716597/decode-the-return-value-from-a-smart-contract-with-web3-py
* etc

**Comment by EightRice** [comment]
thanks for clearing it up for me.
