### ISSUE TITLE
[Not issue] install metamask on chrome debug mode

### ISSUE THREAD

**Issue by thanhnamitit** [gochain/flutter_web3_provider#27]
Hi, I run example code on chrome. But application run on chrome debug mode, so I cannot install metamask there to connect to wallet. Could you please give me a solution to fix this?

**Comment by y-pakorn** [comment]
You can copy the URL from the debug browser and launch it in normal chrome.
Or just run the Flutter with `$ flutter run -d web-server`.

**Comment by thanhnamitit** [comment]
thanks
