### ISSUE TITLE
dart.global.ethers is undefined

### ISSUE THREAD

**Issue by WeDev00** [gochain/flutter_web3_provider#35]
despite having the same syntax as in the example, I get the error in the title

`final Web3Provider provider = Web3Provider(ethereum!);

  final Signer signer = provider.getSigner();
  
  final Contract contract =
      Contract(deployedNftContractAddress, tideNftAbiListed, provider);
      
  final symbol = await contract.symbol();`
  
  when running `final Web3Provider provider = Web3Provider(ethereum!);` 
I get the error dart.global.ethers is undefined.
Below I put all the imports of the file containing this code:

`import 'package:flutter_web3_provider/ethers.dart';

import 'package:http/http.dart' as http;

import 'package:flutter_web3_provider/ethereum.dart';

import 'dart:convert';`

**Comment by treeder** [comment]
Did you import ethers like in the example? https://github.com/gochain/flutter_web3_provider/blob/main/example/lib/main.dart

**Comment by WeDev00** [comment]
yes

**Comment by treeder** [comment]
Did you add this to the HTML? 

```
<script src="https://cdn.ethers.io/lib/ethers-5.0.umd.min.js" type="application/javascript"></script>
```

**Comment by WeDev00** [comment]
I just added it, but I keep getting the same error

**Comment by treeder** [comment]
I'm not sure, might have to debug it yourself. Pull Requests are welcome.

**Comment by WeDev00** [comment]
I solved by downloading and adding manually the script : https://cdn.ethers.io/lib/ethers-5.0.umd.min.js in my project

**Comment by treeder** [comment]
For anyone else finding this, looks like ethers CDN is broken. 

![Image](https://github.com/user-attachments/assets/983a2ed2-7e06-413c-a80a-43dc3541d37c)

Updated README with new CDN.

**Comment by treeder** [comment]
Should all be fixed now, upgrade this package. Go through README again.
