### ISSUE TITLE
Packages version mismatch 

### ISSUE THREAD

**Issue by EightRice** [gochain/flutter_web3_provider#6]
If you try to clone the repo and run it as is, you get 

[Because flutter_web3_provider requires SDK version >=2.12.0 <3.0.0, version solving failed.
pub get failed (1; Because flutter_web3_provider requires SDK version >=2.12.0 <3.0.0, version solving failed.)
exit code 1](url)

Even when you manually set the sdk to >=2.12.0 <3.0.0 , it still fails to get the packages.

**Comment by treeder** [comment]
Are you running the app in the example directory and getting this?  Seems to work for me. Any more details or steps to reproduce?

**Comment by EightRice** [comment]
I left them all without a version number and it worked it out by itself.
