### ISSUE TITLE
Passing gas and value to metamask

### ISSUE THREAD

**Issue by eakdogan** [gochain/flutter_web3_provider#7]
Can you give an example of how to call a payable function; passing the gaslimit, gasprice, value, data.

**Comment by treeder** [comment]
It's in the README:

```
var res =
    await promiseToFuture(callMethod(contract, "transfer", [
    '0x39C5190c09ec04cF09C782bA4311C469473Ffe83',
    "0x" + amount.toString()).toRadixString(16)
    ]));
```

I'm not sure we got to try out overriding gas price and things, but based on ethere.js (which this is using under the hood), it should be passed as a map of overrides in the last slot of that params array. More on that here: https://github.com/ethers-io/ethers.js/issues/563#issuecomment-513599929

**Comment by treeder** [comment]
That method is calling the "transfer" function on an ERC20 contract. So you'd do almost the exact same thing except pass the "tag" value in that array. eg:
 
```js
var res =
    await promiseToFuture(callMethod(contract, "transfer", [
    tag
    ]));
```

**Comment by eakdogan** [comment]
Yes, that's how I have been calling it and it works. But when I make the function payable on the contract I do not know how to pass the message value. Also it gives an error about inability to estimate gas.

**Comment by treeder** [comment]
I see, so you need to be able to fill in the "value" field. Maybe try something like this (untested):

```js
var res =
    await promiseToFuture(callMethod(contract, "transfer", [
    tag
, {value: 1000000000000000000 }
    ]));
```

**Comment by pinpong** [comment]
Hi,

passing the value as describe is not working. Any ideas?

**Comment by eakdogan** [comment]
Haven't been able to do it; tried various ways.  Please post here if you find a way.

**Comment by pinpong** [comment]
try this one:

```js
var res = await promiseToFuture(callMethod(
contract, "transfer", [tag, TxParams(value: "1000000000000000000")]));
```

**Comment by eakdogan** [comment]
Works! Thank you!

**Comment by treeder** [comment]
Thanks @pinpong , added that to the README.
